name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Create env file
        run: |
          touch .env
          echo "${{ secrets.ENV }}" > .env
          cat .env

      - name: Install npm dependencies
        run: npm install

      - name: Run build task
        run: npm run build --if-present
        env:
          CI: false

      - name: Install PM2
        run: npm install -g pm2

      - name: Deploy code Server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i --delete"
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
          EXCLUDE: "/node_modules/"

      - name: PM2 restarts
        run: |
          touch key.pem
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > key.pem
          chmod 400 key.pem
          ssh -i key.pem ${{secrets.USERNAME}}@${{secrets.HOST_DNS}} -p 22 '
          export PATH=$PATH:/home/denys/.nvm/versions/node/v18.18.2/bin
          pm2 kill
          cd /home/denys/instagram-clone-frontend/
          pm2 start npm --name "instagram-clone-frontend" -- start -- --port 3000
          '
